version: "3.9"

services:
  servidor-db:
    build: ./servidor-db
    container_name: servidor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword!
      MYSQL_DATABASE: nvs_db
      MYSQL_USER: nvs_app
      MYSQL_PASSWORD: AppStrongPassword!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nvs-net

  servidor-app:
    build: ./servidor-app
    container_name: servidor-app
    restart: always
    depends_on:
      - servidor-db
    ports:
      - "80:80"
    networks:
      - nvs-net

  servidor-backups:
    build: ./servidor-backups
    container_name: servidor-backups
    restart: always
    depends_on:
      - servidor-db
    volumes:
      - backup_data:/backups
    networks:
      - nvs-net

volumes:
  db_data:
  backup_data:

networks:
  nvs-net:
    driver: bridge
