services:
  servidor-app:
    build: ./servidor-app
    container_name: servidor-app
    ports:
      - "8080:80"
    volumes:
      - ./app/comprobantes:/var/www/html/comprobantes
      - ./app/perfiles:/var/www/html/perfiles
    networks:
      - appnet

  backup:
    build: ./backup
    container_name: sistema_backup
    volumes:
      - ./backup:/backups
    networks:
      - appnet

networks:
  appnet: